{#.:.}
    <div class="row">
        <div class="col-xs-2">
            <a href="/profile/{username}">
                <img src="{?avatar}{avatar}{:else}/img/stockUser.png{/avatar}" class="img-responsive"/>
            </a>
        </div>
        <div class="col-xs-10">
            <div style="line-height: 75px">
                <a href="/profile/{username}" class="userLink">{username}</a>
            </div>
        </div>
    </div>
{/.}